// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/middlewares/compressor/compressor_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCompressor is a mock of Compressor interface.
type MockCompressor struct {
	ctrl     *gomock.Controller
	recorder *MockCompressorMockRecorder
}

// MockCompressorMockRecorder is the mock recorder for MockCompressor.
type MockCompressorMockRecorder struct {
	mock *MockCompressor
}

// NewMockCompressor creates a new mock instance.
func NewMockCompressor(ctrl *gomock.Controller) *MockCompressor {
	mock := &MockCompressor{ctrl: ctrl}
	mock.recorder = &MockCompressorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompressor) EXPECT() *MockCompressorMockRecorder {
	return m.recorder
}

// CompressResponse mocks base method.
func (m *MockCompressor) CompressResponse(w http.ResponseWriter, r *http.Request) http.ResponseWriter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompressResponse", w, r)
	ret0, _ := ret[0].(http.ResponseWriter)
	return ret0
}

// CompressResponse indicates an expected call of CompressResponse.
func (mr *MockCompressorMockRecorder) CompressResponse(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompressResponse", reflect.TypeOf((*MockCompressor)(nil).CompressResponse), w, r)
}

// DecompressRequest mocks base method.
func (m *MockCompressor) DecompressRequest(r *http.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecompressRequest", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecompressRequest indicates an expected call of DecompressRequest.
func (mr *MockCompressorMockRecorder) DecompressRequest(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecompressRequest", reflect.TypeOf((*MockCompressor)(nil).DecompressRequest), r)
}
