// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/mainpagehandler/main_page_service_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMainPageService is a mock of MainPageService interface.
type MockMainPageService struct {
	ctrl     *gomock.Controller
	recorder *MockMainPageServiceMockRecorder
}

// MockMainPageServiceMockRecorder is the mock recorder for MockMainPageService.
type MockMainPageServiceMockRecorder struct {
	mock *MockMainPageService
}

// NewMockMainPageService creates a new mock instance.
func NewMockMainPageService(ctrl *gomock.Controller) *MockMainPageService {
	mock := &MockMainPageService{ctrl: ctrl}
	mock.recorder = &MockMainPageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMainPageService) EXPECT() *MockMainPageServiceMockRecorder {
	return m.recorder
}

// GetMainPage mocks base method.
func (m *MockMainPageService) GetMainPage(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMainPage", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMainPage indicates an expected call of GetMainPage.
func (mr *MockMainPageServiceMockRecorder) GetMainPage(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMainPage", reflect.TypeOf((*MockMainPageService)(nil).GetMainPage), ctx)
}
