package main

// Шаблон генерации файла
const resetTemplate = `// Code generated by reset generator. DO NOT EDIT.
//go:generate go run ./cmd/reset/main.go

package {{ .PackageName }}

{{- if .Imports }}
import (
{{- range .Imports }}
	{{- if .Name }}{{ .Name }} {{ end }}"{{ .Path }}"
{{- end }}
)
{{- end }}

{{- range .Structs }}
func (x *{{ .Name }}) Reset() {
{{ .Body }}
}
{{- end }}
`
