// Code generated by reset generator. DO NOT EDIT.
//go:generate go run ./cmd/reset/main.go

package config

func (x *AgentFlags) Reset() {
	x.ServerAddr = ""
	x.ReportInterval = 0
	x.PollingInterval = 0
	x.LogLevel = ""
	x.SecretKey = ""
	x.RateLimit = 0
	x.MaxRetries = 0
	x.RetryDelays = x.RetryDelays[:0]
}
func (x *ServerFlags) Reset() {
	x.ServerAddr = ""
	x.LogLevel = ""
	x.StoreInterval = 0
	x.FileStoragePath = ""
	x.Restore = false
	x.DatabaseDSN = ""
	x.SecretKet = ""
	x.RateLimit = 0
	x.MaxRetries = 0
	x.RetryDelays = x.RetryDelays[:0]
	x.AuditFile = ""
	x.AuditURL = ""
}
